'use client'
import Sidebar from '@/components/Sidebar'
import { useState } from 'react'
import { useReports, Report, ReportType } from '@/context/ReportContext'
import { useToast } from '@/context/ToastContext'
import ReportModal from '@/components/ReportModal'
import ReportPreviewModal from '@/components/ReportPreviewModal'

export default function Reports() {
  const [activeTab, setActiveTab] = useState('predefined')
  const [showCustomModal, setShowCustomModal] = useState(false)
  const [previewReport, setPreviewReport] = useState<Report | null>(null)
  const [dateRange, setDateRange] = useState('Last 30 days')
  const [showDateMenu, setShowDateMenu] = useState(false)

  const { reports, customReports, addReport, deleteReport } = useReports()
  const { addToast, removeToast } = useToast()

  const handleGeneratePredefined = async (name: string, type: ReportType = 'PDF') => {
    const toastId = addToast(`Generating ${name}...`, 'loading')
    await addReport({
      name,
      type,
      period: dateRange,
      size: `${(Math.random() * 4 + 1).toFixed(1)} MB`
    })
    removeToast(toastId)
    addToast(`"${name}" report is ready!`, 'success')
  }

  const handleDownload = (report: Report) => {
    addToast(`Downloading ${report.name}...`, 'info')
    
    let fileContent = "data:text/plain;charset=utf-8,"
    fileContent += `Report Name: ${report.name}\n`
    fileContent += `Type: ${report.type}\n`
    fileContent += `Period: ${report.period}\n`
    fileContent += `Date Generated: ${report.dateGenerated}\n\n`
    fileContent += `(Mock report content generated by RecruitIQ)`

    setTimeout(() => {
      const encodedUri = encodeURI(fileContent)
      const link = document.createElement("a")
      link.setAttribute("href", encodedUri)
      link.setAttribute("download", `${report.name.replace(/ /g, '_')}_Report.txt`)
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      addToast(`Download complete`, 'success')
    }, 1500)
  }

  const handleDelete = (id: string) => {
    deleteReport(id)
    addToast('Report deleted', 'info')
  }

  const handleShare = (report: Report) => {
    addToast(`Share link copied to clipboard!`, 'success')
  }

  const dateRanges = ['Last 7 days', 'Last 30 days', 'Last 90 days', 'This Year']

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: '#0f1117' }}>
      <Sidebar />
      
      <main className="main-content">
        {/* Header Section */}
        <header style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '16px', marginBottom: '32px' }}>
          <div>
            <h1 style={{ color: '#f1f5f9', fontSize: '24px', fontWeight: 700, letterSpacing: '-0.02em', fontFamily: 'Space Grotesk, sans-serif' }}>
              Reports
            </h1>
            <p style={{ color: '#94a3b8', fontSize: '14px', marginTop: '6px', fontFamily: 'DM Sans, sans-serif' }}>
              Generate and download performance reports
            </p>
          </div>
          
          <div style={{ display: 'flex', gap: '12px' }}>
            {/* Date Dropdown */}
            <div style={{ position: 'relative' }}>
              <button 
                onClick={() => setShowDateMenu(!showDateMenu)}
                style={{
                  display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 16px', borderRadius: '12px',
                  background: '#151822', border: '1px solid rgba(255,255,255,0.08)',
                  color: '#94a3b8', fontSize: '13px', cursor: 'pointer', fontFamily: 'Space Grotesk, sans-serif'
                }}
              >
                <span style={{ fontSize: '14px' }}>📅</span>
                <span>{dateRange}</span>
                <span style={{ fontSize: '10px' }}>▾</span>
              </button>
              {showDateMenu && (
                <div style={{
                  position: 'absolute', top: '110%', right: 0, zIndex: 100,
                  minWidth: '180px', borderRadius: '12px', overflow: 'hidden',
                  background: '#1a1f2e', border: '1px solid rgba(255,255,255,0.08)',
                }}>
                  {dateRanges.map(range => (
                    <button key={range} onClick={() => { setDateRange(range); setShowDateMenu(false) }} style={{
                      width: '100%', padding: '10px 16px', textAlign: 'left', border: 'none', cursor: 'pointer',
                      background: dateRange === range ? 'rgba(99,102,241,0.15)' : 'transparent',
                      color: dateRange === range ? '#818cf8' : '#94a3b8',
                      borderBottom: '1px solid rgba(255,255,255,0.04)', fontSize: '13px', fontFamily: 'Space Grotesk, sans-serif'
                    }}>
                      {range}
                    </button>
                  ))}
                </div>
              )}
            </div>
            
            <button 
              onClick={() => setShowCustomModal(true)}
              style={{
                background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
                color: 'white', border: 'none', borderRadius: '12px',
                padding: '10px 20px', fontSize: '13px', fontWeight: 600,
                cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px',
                fontFamily: 'Space Grotesk, sans-serif', transition: 'transform 0.1s'
              }}
              onMouseDown={e => e.currentTarget.style.transform = 'scale(0.96)'}
              onMouseUp={e => e.currentTarget.style.transform = 'scale(1)'}
              onMouseLeave={e => e.currentTarget.style.transform = 'scale(1)'}
            >
              + Custom Report
            </button>
          </div>
        </header>

        {/* Tabs */}
        <div style={{ display: 'flex', gap: '24px', borderBottom: '1px solid rgba(255,255,255,0.08)', marginBottom: '32px' }}>
          <button 
            onClick={() => setActiveTab('predefined')}
            style={{
              background: 'none', border: 'none', padding: '0 0 12px 0',
              color: activeTab === 'predefined' ? '#818cf8' : '#64748b',
              fontSize: '14px', fontWeight: 500, cursor: 'pointer',
              borderBottom: activeTab === 'predefined' ? '2px solid #818cf8' : '2px solid transparent',
              fontFamily: 'Space Grotesk, sans-serif', transition: 'all 0.2s'
            }}
          >
            Predefined Reports
          </button>
          <button 
            onClick={() => setActiveTab('custom')}
            style={{
              background: 'none', border: 'none', padding: '0 0 12px 0',
              color: activeTab === 'custom' ? '#818cf8' : '#64748b',
              fontSize: '14px', fontWeight: 500, cursor: 'pointer',
              borderBottom: activeTab === 'custom' ? '2px solid #818cf8' : '2px solid transparent',
              fontFamily: 'Space Grotesk, sans-serif', transition: 'all 0.2s'
            }}
          >
            Custom Reports
          </button>
        </div>

        {activeTab === 'predefined' ? (
          <div className="grid-3" style={{ marginBottom: '48px' }}>
            <ReportCard 
              icon="%" iconColor="#f43f5e" iconBg="rgba(244,63,94,0.1)"
              title="Performance Summary" desc="Overview of key metrics and KPIs" time="2 hours ago"
              onGenerate={() => handleGeneratePredefined('Performance Summary', 'PDF')}
            />
            <ReportCard 
              icon="📈" iconColor="#8b5cf6" iconBg="rgba(139,92,246,0.1)"
              title="Campaign Performance" desc="Detailed campaign-wise analysis" time="1 day ago"
              onGenerate={() => handleGeneratePredefined('Campaign Performance', 'PDF')}
            />
            <ReportCard 
              icon="💳" iconColor="#10b981" iconBg="rgba(16,185,129,0.1)"
              title="Channel Analysis" desc="Performance breakdown by channels" time="3 hours ago"
              onGenerate={() => handleGeneratePredefined('Channel Analysis', 'Excel')}
            />
            <ReportCard 
              icon="B" iconColor="#eab308" iconBg="rgba(234,179,8,0.1)"
              title="Cost Analysis" desc="Spend analysis and cost breakdown" time="5 hours ago"
              onGenerate={() => handleGeneratePredefined('Cost Analysis', 'Excel')}
            />
            <ReportCard 
              icon=" funnel" iconColor="#10b981" iconBg="rgba(16,185,129,0.1)"
              title="Conversion Report" desc="Conversion funnel and metrics" time="1 day ago"
              onGenerate={() => handleGeneratePredefined('Conversion Report', 'PDF')}
            />
            <ReportCard 
              icon="📍" iconColor="#3b82f6" iconBg="rgba(59,130,246,0.1)"
              title="Location Report" desc="Performance by locations" time="2 days ago"
              onGenerate={() => handleGeneratePredefined('Location Report', 'CSV')}
            />
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px', marginBottom: '48px' }}>
            {customReports.length === 0 ? (
              <div style={{ gridColumn: '1 / -1', padding: '48px', textAlign: 'center', background: '#151822', borderRadius: '16px', border: '1px dashed rgba(255,255,255,0.1)' }}>
                <p style={{ color: '#94a3b8', fontSize: '14px', fontFamily: 'DM Sans, sans-serif' }}>No custom reports found.</p>
                <button onClick={() => setShowCustomModal(true)} style={{ marginTop: '16px', padding: '8px 16px', background: 'transparent', border: '1px solid #818cf8', color: '#818cf8', borderRadius: '8px', cursor: 'pointer', fontFamily: 'Space Grotesk, sans-serif' }}>Create one now</button>
              </div>
            ) : customReports.map(cr => (
              <div key={cr.id} style={{ background: '#151822', borderRadius: '16px', padding: '24px', border: '1px solid rgba(255,255,255,0.03)', display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <h3 style={{ color: '#f8fafc', fontSize: '15px', fontWeight: 600, fontFamily: 'Space Grotesk, sans-serif' }}>{cr.name}</h3>
                <p style={{ color: '#64748b', fontSize: '12px' }}>{cr.period} • {cr.type}</p>
                <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap', marginTop: '8px' }}>
                  {cr.metrics?.map(m => <span key={m} style={{ background: '#1e293b', color: '#cbd5e1', padding: '2px 6px', borderRadius: '4px', fontSize: '10px' }}>{m}</span>)}
                </div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 'auto', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.03)' }}>
                  <span style={{ color: '#475569', fontSize: '12px' }}>Last: {cr.dateGenerated.split(',')[0]}</span>
                  <button onClick={() => setPreviewReport(cr)} style={{ background: 'none', border: 'none', color: '#818cf8', fontSize: '13px', fontWeight: 600, cursor: 'pointer', fontFamily: 'Space Grotesk, sans-serif' }}>View</button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Recent Reports Table */}
        <div>
          <h2 style={{ color: '#e2e8f0', fontSize: '14px', fontWeight: 600, marginBottom: '16px', fontFamily: 'Space Grotesk, sans-serif', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ color: '#10b981', fontSize: '10px' }}>▶</span> Recent Reports
          </h2>
          
          <div style={{ background: 'transparent', overflow: 'hidden' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif' }}>REPORT NAME</th>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif' }}>TYPE</th>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif' }}>DATE GENERATED</th>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif' }}>PERIOD</th>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif' }}>SIZE</th>
                  <th style={{ padding: '12px 0', color: '#64748b', fontSize: '11px', fontWeight: 600, letterSpacing: '0.05em', fontFamily: 'Space Grotesk, sans-serif', textAlign: 'right' }}>ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {reports.length === 0 && (
                  <tr>
                    <td colSpan={6} style={{ padding: '32px 0', textAlign: 'center', color: '#64748b', fontSize: '13px' }}>No reports generated yet.</td>
                  </tr>
                )}
                {reports.map(report => (
                  <tr key={report.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                    <td style={{ padding: '16px 0', color: '#f8fafc', fontSize: '13px', fontWeight: 500, display: 'flex', alignItems: 'center', gap: '8px' }}>
                      {report.status === 'Generating' && <span style={{ display: 'inline-block', width: '8px', height: '8px', borderRadius: '50%', background: '#3b82f6', animation: 'pulse 1.5s infinite' }}></span>}
                      {report.name}
                    </td>
                    <td style={{ padding: '16px 0', color: '#94a3b8', fontSize: '13px' }}>
                      <span style={{ background: report.type === 'PDF' ? 'rgba(239,68,68,0.1)' : report.type === 'Excel' ? 'rgba(16,185,129,0.1)' : 'rgba(59,130,246,0.1)', color: report.type === 'PDF' ? '#f87171' : report.type === 'Excel' ? '#34d399' : '#60a5fa', padding: '2px 6px', borderRadius: '4px', fontSize: '11px' }}>
                        {report.type}
                      </span>
                    </td>
                    <td style={{ padding: '16px 0', color: '#94a3b8', fontSize: '13px' }}>{report.dateGenerated}</td>
                    <td style={{ padding: '16px 0', color: '#94a3b8', fontSize: '13px' }}>{report.period}</td>
                    <td style={{ padding: '16px 0', color: '#94a3b8', fontSize: '13px' }}>
                      {report.status === 'Generating' ? <span style={{ color: '#3b82f6', fontSize: '11px' }}>Generating...</span> : report.size}
                    </td>
                    <td style={{ padding: '16px 0', textAlign: 'right' }}>
                      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '6px' }}>
                        {report.status === 'Generating' ? (
                          <span style={{ color: '#475569', fontSize: '12px' }}>Processing</span>
                        ) : (
                          <>
                            <ActionButton icon="👁" title="Preview" onClick={() => setPreviewReport(report)} />
                            <ActionButton icon="📥" title="Download" onClick={() => handleDownload(report)} />
                            <ActionButton icon="🔗" title="Share" onClick={() => handleShare(report)} />
                            <ActionButton icon="🗑" title="Delete" onClick={() => handleDelete(report.id)} danger />
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>

      {showCustomModal && <ReportModal onClose={() => setShowCustomModal(false)} />}
      {previewReport && <ReportPreviewModal report={previewReport} onClose={() => setPreviewReport(null)} />}
    </div>
  )
}

function ReportCard({ icon, iconColor, iconBg, title, desc, time, onGenerate }: any) {
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerate = async () => {
    setIsGenerating(true)
    await onGenerate()
    setIsGenerating(false)
  }

  return (
    <div style={{
      background: '#151822', borderRadius: '16px', padding: '24px',
      border: '1px solid rgba(255,255,255,0.03)', display: 'flex', flexDirection: 'column', gap: '20px',
      transition: 'transform 0.2s, box-shadow 0.2s'
    }}
    onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.2)' }}
    onMouseLeave={e => { e.currentTarget.style.transform = 'none'; e.currentTarget.style.boxShadow = 'none' }}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
        <div style={{
          width: '42px', height: '42px', borderRadius: '12px', background: iconBg,
          color: iconColor, display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: '18px', fontWeight: 'bold'
        }}>
          {icon === ' funnel' ? (
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>
          ) : icon}
        </div>
        <div>
          <h3 style={{ color: '#f8fafc', fontSize: '15px', fontWeight: 600, fontFamily: 'Space Grotesk, sans-serif' }}>{title}</h3>
          <p style={{ color: '#64748b', fontSize: '12px', marginTop: '6px', lineHeight: '1.5' }}>{desc}</p>
        </div>
      </div>
      
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 'auto', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.03)' }}>
        <span style={{ color: '#475569', fontSize: '12px' }}>Last generated: {time}</span>
        <button 
          onClick={handleGenerate} 
          disabled={isGenerating}
          style={{
            background: 'none', border: 'none', color: isGenerating ? '#64748b' : '#818cf8', fontSize: '13px',
            fontWeight: 600, cursor: isGenerating ? 'not-allowed' : 'pointer', fontFamily: 'Space Grotesk, sans-serif',
            display: 'flex', alignItems: 'center', gap: '6px'
          }}
        >
          {isGenerating ? '⏳ Generating...' : 'Generate'}
        </button>
      </div>
    </div>
  )
}

function ActionButton({ icon, onClick, title, danger = false }: any) {
  return (
    <button 
      onClick={onClick} 
      title={title}
      style={{
        background: danger ? 'rgba(239,68,68,0.1)' : '#1a1f2e', 
        border: '1px solid rgba(255,255,255,0.05)', borderRadius: '6px',
        width: '32px', height: '32px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        color: danger ? '#ef4444' : '#e2e8f0', cursor: 'pointer', transition: 'all 0.2s',
        fontSize: '14px'
      }}
      onMouseEnter={e => e.currentTarget.style.background = danger ? 'rgba(239,68,68,0.2)' : '#2a3042'}
      onMouseLeave={e => e.currentTarget.style.background = danger ? 'rgba(239,68,68,0.1)' : '#1a1f2e'}
    >
      {icon === '📥' ? <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg> : 
       icon === '👁' ? <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg> :
       icon === '🔗' ? <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg> :
       icon === '🗑' ? <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg> : icon}
    </button>
  )
}
